/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author 25666
 */
public class vista extends javax.swing.JFrame {

    private boolean igual, inicio = true, operacion1, operacion2;
    private double a, b, c, MEMORIA = 0, memoriaMAS = 0, memoriaMENOS = 0, valor1, valor2;
    private String cadena = "", resultado = "0", funciones, tipoOperaciones;
    
    public vista() {
        initComponents();
        setLocationRelativeTo(null);
        Memory.setVisible(false);
        cadena = "";
        resultado = "0";
        memoriaMAS = 0;
        memoriaMENOS = 0;
        MEMORIA = 0;
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        JPanel = new javax.swing.JPanel();
        vistaPrincipal = new javax.swing.JTextField();
        vistaSecundaria = new javax.swing.JTextField();
        Memory = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Numero1 = new javax.swing.JButton();
        Numero7 = new javax.swing.JButton();
        Numero8 = new javax.swing.JButton();
        Numero2 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        Numero5 = new javax.swing.JButton();
        Numero0 = new javax.swing.JButton();
        Numero6 = new javax.swing.JButton();
        Numero9 = new javax.swing.JButton();
        Numero4 = new javax.swing.JButton();
        Numero3 = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        division = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resultados = new javax.swing.JButton();
        raizcuadrada = new javax.swing.JButton();
        unoentrex = new javax.swing.JButton();
        memoriamenos = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        MasyMenos = new javax.swing.JButton();
        memoriamas = new javax.swing.JButton();
        parentesis1 = new javax.swing.JButton();
        memorias = new javax.swing.JButton();
        flechitaXD = new javax.swing.JButton();
        memoriac = new javax.swing.JButton();
        arcotengente = new javax.swing.JButton();
        tangente = new javax.swing.JButton();
        Borrado = new javax.swing.JButton();
        memoriar = new javax.swing.JButton();
        arcoseno = new javax.swing.JButton();
        seno = new javax.swing.JButton();
        arcocoseno = new javax.swing.JButton();
        coseno = new javax.swing.JButton();
        aGradianes = new javax.swing.JButton();
        NumeroEuler = new javax.swing.JButton();
        NumeroPi = new javax.swing.JButton();
        xelevadoalcuadrado = new javax.swing.JButton();
        xelevadoaalgo = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        aRadianes = new javax.swing.JButton();
        elevado10 = new javax.swing.JButton();
        imaginario = new javax.swing.JButton();
        logaritmo = new javax.swing.JButton();
        xelevadoalcubo = new javax.swing.JButton();
        parentesis2 = new javax.swing.JButton();
        raizdealgo = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 204));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel.setBackground(new java.awt.Color(255, 255, 255));
        JPanel.setForeground(new java.awt.Color(255, 255, 255));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vistaPrincipal.setEditable(false);
        vistaPrincipal.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        vistaPrincipal.setForeground(new java.awt.Color(45, 45, 45));
        vistaPrincipal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vistaPrincipal.setBorder(null);
        vistaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaPrincipalActionPerformed(evt);
            }
        });
        JPanel.add(vistaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 480, 40));

        vistaSecundaria.setEditable(false);
        vistaSecundaria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vistaSecundaria.setForeground(new java.awt.Color(36, 36, 36));
        vistaSecundaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vistaSecundaria.setBorder(null);
        vistaSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaSecundariaActionPerformed(evt);
            }
        });
        JPanel.add(vistaSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 450, 20));

        Memory.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        Memory.setForeground(new java.awt.Color(36, 36, 36));
        Memory.setText("M");
        JPanel.add(Memory, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        getContentPane().add(JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 150));

        jPanel4.setBackground(new java.awt.Color(242, 241, 255));

        Numero1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero1.setText("1");
        Numero1.setBorder(null);
        Numero1.setFocusPainted(false);
        Numero1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero1ActionPerformed(evt);
            }
        });

        Numero7.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero7.setText("7");
        Numero7.setBorder(null);
        Numero7.setFocusPainted(false);
        Numero7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero7ActionPerformed(evt);
            }
        });

        Numero8.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero8.setText("8");
        Numero8.setBorder(null);
        Numero8.setFocusPainted(false);
        Numero8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero8ActionPerformed(evt);
            }
        });

        Numero2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero2.setText("2");
        Numero2.setBorder(null);
        Numero2.setFocusPainted(false);
        Numero2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero2ActionPerformed(evt);
            }
        });

        punto.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        punto.setText(".");
        punto.setBorder(null);
        punto.setFocusPainted(false);
        punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        punto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        punto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        Numero5.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero5.setText("5");
        Numero5.setBorder(null);
        Numero5.setFocusPainted(false);
        Numero5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero5ActionPerformed(evt);
            }
        });

        Numero0.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeNumeros.png"))); // NOI18N
        Numero0.setText("0");
        Numero0.setBorder(null);
        Numero0.setFocusPainted(false);
        Numero0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeNumeros.png"))); // NOI18N
        Numero0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeNumeros2.png"))); // NOI18N
        Numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero0ActionPerformed(evt);
            }
        });

        Numero6.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero6.setText("6");
        Numero6.setBorder(null);
        Numero6.setFocusPainted(false);
        Numero6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero6ActionPerformed(evt);
            }
        });

        Numero9.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero9.setText("9");
        Numero9.setBorder(null);
        Numero9.setFocusPainted(false);
        Numero9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero9ActionPerformed(evt);
            }
        });

        Numero4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero4.setText("4");
        Numero4.setBorder(null);
        Numero4.setFocusPainted(false);
        Numero4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero4ActionPerformed(evt);
            }
        });

        Numero3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Numero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero3.setText("3");
        Numero3.setBorder(null);
        Numero3.setFocusPainted(false);
        Numero3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Numero3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros.png"))); // NOI18N
        Numero3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Numeros2.png"))); // NOI18N
        Numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero3ActionPerformed(evt);
            }
        });

        multiplicacion.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        multiplicacion.setText("×");
        multiplicacion.setBorder(null);
        multiplicacion.setFocusPainted(false);
        multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplicacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores2.png"))); // NOI18N
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        resta.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        resta.setText("-");
        resta.setBorder(null);
        resta.setFocusPainted(false);
        resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores2.png"))); // NOI18N
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        division.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        division.setText("÷");
        division.setBorder(null);
        division.setFocusPainted(false);
        division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        division.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores2.png"))); // NOI18N
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        suma.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        suma.setText("+");
        suma.setBorder(null);
        suma.setFocusPainted(false);
        suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores.png"))); // NOI18N
        suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Operadores2.png"))); // NOI18N
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resultados.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        resultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeOtros.png"))); // NOI18N
        resultados.setText("=");
        resultados.setBorder(null);
        resultados.setFocusPainted(false);
        resultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeOtros.png"))); // NOI18N
        resultados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LargeOtros2.png"))); // NOI18N
        resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosActionPerformed(evt);
            }
        });

        raizcuadrada.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        raizcuadrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        raizcuadrada.setText("√");
        raizcuadrada.setBorder(null);
        raizcuadrada.setFocusPainted(false);
        raizcuadrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raizcuadrada.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        raizcuadrada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        raizcuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizcuadradaActionPerformed(evt);
            }
        });

        unoentrex.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        unoentrex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        unoentrex.setText("1/x");
        unoentrex.setBorder(null);
        unoentrex.setFocusPainted(false);
        unoentrex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unoentrex.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        unoentrex.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        unoentrex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoentrexActionPerformed(evt);
            }
        });

        memoriamenos.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        memoriamenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriamenos.setText("M-");
        memoriamenos.setBorder(null);
        memoriamenos.setFocusPainted(false);
        memoriamenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memoriamenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriamenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        memoriamenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriamenosActionPerformed(evt);
            }
        });

        porcentaje.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        porcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        porcentaje.setText("%");
        porcentaje.setBorder(null);
        porcentaje.setFocusPainted(false);
        porcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        porcentaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        porcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        MasyMenos.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        MasyMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        MasyMenos.setText("±");
        MasyMenos.setBorder(null);
        MasyMenos.setFocusPainted(false);
        MasyMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MasyMenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        MasyMenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        MasyMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasyMenosActionPerformed(evt);
            }
        });

        memoriamas.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        memoriamas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriamas.setText("M+");
        memoriamas.setBorder(null);
        memoriamas.setFocusPainted(false);
        memoriamas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memoriamas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriamas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        memoriamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriamasActionPerformed(evt);
            }
        });

        parentesis1.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        parentesis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        parentesis1.setText("(");
        parentesis1.setBorder(null);
        parentesis1.setFocusPainted(false);
        parentesis1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parentesis1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        parentesis1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        parentesis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis1ActionPerformed(evt);
            }
        });

        memorias.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        memorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memorias.setText("MS");
        memorias.setBorder(null);
        memorias.setFocusPainted(false);
        memorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memorias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memorias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        memorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriasActionPerformed(evt);
            }
        });

        flechitaXD.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        flechitaXD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        flechitaXD.setText("←");
        flechitaXD.setBorder(null);
        flechitaXD.setFocusPainted(false);
        flechitaXD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flechitaXD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        flechitaXD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        flechitaXD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechitaXDActionPerformed(evt);
            }
        });

        memoriac.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        memoriac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriac.setText("MC");
        memoriac.setBorder(null);
        memoriac.setFocusPainted(false);
        memoriac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memoriac.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriac.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        memoriac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriacActionPerformed(evt);
            }
        });

        arcotengente.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        arcotengente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcotengente.setText("atan");
        arcotengente.setBorder(null);
        arcotengente.setFocusPainted(false);
        arcotengente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arcotengente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcotengente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        arcotengente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcotengenteActionPerformed(evt);
            }
        });

        tangente.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        tangente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        tangente.setText("tan");
        tangente.setBorder(null);
        tangente.setFocusPainted(false);
        tangente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tangente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        tangente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangenteActionPerformed(evt);
            }
        });

        Borrado.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        Borrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        Borrado.setText("CE");
        Borrado.setBorder(null);
        Borrado.setFocusPainted(false);
        Borrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Borrado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        Borrado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        Borrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorradoActionPerformed(evt);
            }
        });

        memoriar.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        memoriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriar.setText("MR");
        memoriar.setBorder(null);
        memoriar.setFocusPainted(false);
        memoriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        memoriar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        memoriar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        memoriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriarActionPerformed(evt);
            }
        });

        arcoseno.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        arcoseno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcoseno.setText("asin");
        arcoseno.setBorder(null);
        arcoseno.setFocusPainted(false);
        arcoseno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arcoseno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcoseno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        arcoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcosenoActionPerformed(evt);
            }
        });

        seno.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        seno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        seno.setText("sin");
        seno.setBorder(null);
        seno.setFocusPainted(false);
        seno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        seno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoActionPerformed(evt);
            }
        });

        arcocoseno.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        arcocoseno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcocoseno.setText("acos");
        arcocoseno.setBorder(null);
        arcocoseno.setFocusPainted(false);
        arcocoseno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arcocoseno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        arcocoseno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        arcocoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcocosenoActionPerformed(evt);
            }
        });

        coseno.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        coseno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        coseno.setText("cos");
        coseno.setBorder(null);
        coseno.setFocusPainted(false);
        coseno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coseno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        coseno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosenoActionPerformed(evt);
            }
        });

        aGradianes.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        aGradianes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        aGradianes.setText("grad");
        aGradianes.setBorder(null);
        aGradianes.setFocusPainted(false);
        aGradianes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aGradianes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        aGradianes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        aGradianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aGradianesActionPerformed(evt);
            }
        });

        NumeroEuler.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        NumeroEuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        NumeroEuler.setText("e");
        NumeroEuler.setBorder(null);
        NumeroEuler.setFocusPainted(false);
        NumeroEuler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NumeroEuler.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        NumeroEuler.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        NumeroEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroEulerActionPerformed(evt);
            }
        });

        NumeroPi.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        NumeroPi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        NumeroPi.setText("π");
        NumeroPi.setBorder(null);
        NumeroPi.setFocusPainted(false);
        NumeroPi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NumeroPi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        NumeroPi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        NumeroPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroPiActionPerformed(evt);
            }
        });

        xelevadoalcuadrado.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        xelevadoalcuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        xelevadoalcuadrado.setText("x²");
        xelevadoalcuadrado.setBorder(null);
        xelevadoalcuadrado.setFocusPainted(false);
        xelevadoalcuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xelevadoalcuadrado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        xelevadoalcuadrado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        xelevadoalcuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xelevadoalcuadradoActionPerformed(evt);
            }
        });

        xelevadoaalgo.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        xelevadoaalgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xy.png"))); // NOI18N
        xelevadoaalgo.setBorder(null);
        xelevadoaalgo.setFocusPainted(false);
        xelevadoaalgo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xelevadoaalgo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xy.png"))); // NOI18N
        xelevadoaalgo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xy2.png"))); // NOI18N
        xelevadoaalgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xelevadoaalgoActionPerformed(evt);
            }
        });

        exp.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        exp.setText("ln");
        exp.setBorder(null);
        exp.setFocusPainted(false);
        exp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        exp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });

        aRadianes.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        aRadianes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        aRadianes.setText("rad");
        aRadianes.setBorder(null);
        aRadianes.setFocusPainted(false);
        aRadianes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aRadianes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        aRadianes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        aRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRadianesActionPerformed(evt);
            }
        });

        elevado10.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        elevado10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10x.png"))); // NOI18N
        elevado10.setBorder(null);
        elevado10.setFocusPainted(false);
        elevado10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        elevado10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10x.png"))); // NOI18N
        elevado10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10x2.png"))); // NOI18N
        elevado10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevado10ActionPerformed(evt);
            }
        });

        imaginario.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        imaginario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        imaginario.setText("n!");
        imaginario.setBorder(null);
        imaginario.setFocusPainted(false);
        imaginario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imaginario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        imaginario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        imaginario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imaginarioActionPerformed(evt);
            }
        });

        logaritmo.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        logaritmo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        logaritmo.setText("log");
        logaritmo.setBorder(null);
        logaritmo.setFocusPainted(false);
        logaritmo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logaritmo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        logaritmo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        logaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logaritmoActionPerformed(evt);
            }
        });

        xelevadoalcubo.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        xelevadoalcubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        xelevadoalcubo.setText("x³");
        xelevadoalcubo.setBorder(null);
        xelevadoalcubo.setFocusPainted(false);
        xelevadoalcubo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xelevadoalcubo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        xelevadoalcubo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        xelevadoalcubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xelevadoalcuboActionPerformed(evt);
            }
        });

        parentesis2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        parentesis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        parentesis2.setText(")");
        parentesis2.setBorder(null);
        parentesis2.setFocusPainted(false);
        parentesis2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parentesis2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros.png"))); // NOI18N
        parentesis2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otros2.png"))); // NOI18N
        parentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis2ActionPerformed(evt);
            }
        });

        raizdealgo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        raizdealgo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/raizcubica.png"))); // NOI18N
        raizdealgo.setBorder(null);
        raizdealgo.setFocusPainted(false);
        raizdealgo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raizdealgo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/raizcubica.png"))); // NOI18N
        raizdealgo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/raizcubica2.png"))); // NOI18N
        raizdealgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizdealgoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(arcocoseno)
                        .addGap(6, 6, 6)
                        .addComponent(arcoseno)
                        .addGap(6, 6, 6)
                        .addComponent(arcotengente)
                        .addGap(6, 6, 6)
                        .addComponent(flechitaXD)
                        .addGap(6, 6, 6)
                        .addComponent(Borrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MasyMenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raizcuadrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unoentrex))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(NumeroEuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aGradianes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xelevadoalcuadrado)
                        .addGap(6, 6, 6)
                        .addComponent(Numero4)
                        .addGap(6, 6, 6)
                        .addComponent(Numero5)
                        .addGap(6, 6, 6)
                        .addComponent(Numero6)
                        .addGap(6, 6, 6)
                        .addComponent(multiplicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parentesis1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(coseno)
                                .addGap(6, 6, 6)
                                .addComponent(seno)
                                .addGap(6, 6, 6)
                                .addComponent(tangente)
                                .addGap(6, 6, 6)
                                .addComponent(memoriac)
                                .addGap(6, 6, 6)
                                .addComponent(memoriar)
                                .addGap(6, 6, 6)
                                .addComponent(memorias)
                                .addGap(6, 6, 6)
                                .addComponent(memoriamas)
                                .addGap(6, 6, 6)
                                .addComponent(memoriamenos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(NumeroPi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(raizdealgo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xelevadoaalgo)
                                .addGap(6, 6, 6)
                                .addComponent(Numero7)
                                .addGap(6, 6, 6)
                                .addComponent(Numero8)
                                .addGap(6, 6, 6)
                                .addComponent(Numero9)
                                .addGap(6, 6, 6)
                                .addComponent(division)
                                .addGap(6, 6, 6)
                                .addComponent(porcentaje))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imaginario)
                                    .addComponent(elevado10))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aRadianes)
                                    .addComponent(exp))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xelevadoalcubo)
                                    .addComponent(logaritmo))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Numero1)
                                        .addGap(6, 6, 6)
                                        .addComponent(Numero2))
                                    .addComponent(Numero0))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Numero3)
                                    .addComponent(punto))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(resta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(parentesis2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(suma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resultados)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coseno)
                    .addComponent(seno)
                    .addComponent(tangente)
                    .addComponent(memoriac)
                    .addComponent(memoriar)
                    .addComponent(memorias)
                    .addComponent(memoriamas)
                    .addComponent(memoriamenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arcocoseno)
                    .addComponent(arcoseno)
                    .addComponent(arcotengente)
                    .addComponent(flechitaXD)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Borrado)
                        .addComponent(MasyMenos)
                        .addComponent(raizcuadrada)
                        .addComponent(unoentrex)))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumeroPi)
                    .addComponent(xelevadoaalgo)
                    .addComponent(Numero7)
                    .addComponent(Numero8)
                    .addComponent(Numero9)
                    .addComponent(division)
                    .addComponent(porcentaje)
                    .addComponent(raizdealgo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroEuler)
                            .addComponent(xelevadoalcuadrado)
                            .addComponent(Numero4)
                            .addComponent(Numero5)
                            .addComponent(Numero6)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(multiplicacion)
                                .addComponent(parentesis1)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(imaginario)
                                .addGap(6, 6, 6)
                                .addComponent(elevado10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(aRadianes)
                                .addGap(6, 6, 6)
                                .addComponent(exp))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(xelevadoalcubo)
                                .addGap(6, 6, 6)
                                .addComponent(logaritmo))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Numero1)
                                    .addComponent(Numero2))
                                .addGap(6, 6, 6)
                                .addComponent(Numero0))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Numero3)
                                .addGap(6, 6, 6)
                                .addComponent(punto))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resta)
                                    .addComponent(parentesis2))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suma)
                                    .addComponent(resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(aGradianes)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero1ActionPerformed
        
        cadena = cadena+"1";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_Numero1ActionPerformed

    private void Numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero7ActionPerformed

        cadena = cadena+"7";
        vistaPrincipal.setText(cadena);

    }//GEN-LAST:event_Numero7ActionPerformed

    private void Numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero8ActionPerformed

        cadena = cadena+"8";
        vistaPrincipal.setText(cadena);

    }//GEN-LAST:event_Numero8ActionPerformed

    private void Numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero2ActionPerformed

        cadena = cadena+"2";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_Numero2ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed

        //if(vistaPrincipal.getText().contains(".")){
            
        //}else{
            cadena = cadena+".";
            vistaPrincipal.setText(cadena);
        //}

    }//GEN-LAST:event_puntoActionPerformed

    private void Numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero5ActionPerformed

        cadena=cadena+"5";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_Numero5ActionPerformed

    private void Numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero0ActionPerformed

        cadena = cadena+"0";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_Numero0ActionPerformed

    private void Numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero6ActionPerformed

        cadena = cadena+"6";
        vistaPrincipal.setText(cadena);

    }//GEN-LAST:event_Numero6ActionPerformed

    private void Numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero9ActionPerformed

        cadena = cadena+"9";
        vistaPrincipal.setText(cadena);

    }//GEN-LAST:event_Numero9ActionPerformed

    private void Numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero4ActionPerformed

        cadena = cadena+"4";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_Numero4ActionPerformed

    private void Numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero3ActionPerformed

        cadena = cadena+"3";
        vistaPrincipal.setText(cadena);

    }//GEN-LAST:event_Numero3ActionPerformed

    /*if(inicio){
            vistaPrincipal.setText(" ");
            vistaPrincipal.setText("3");
            inicio = false;
        }else{
            vistaPrincipal.setText(vistaPrincipal.getText() + "3");
        }*/
    
    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        
        cadena = cadena+"*";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed

        cadena = cadena+"-";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_restaActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed

        cadena = cadena+"/";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_divisionActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
       
        cadena = cadena+"+";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_sumaActionPerformed

    
    /*private void Operaciones(double valor1, double valor2){
        
        
        switch(tipoOperaciones){
            case "+":
                resultado = valor1 + valor2;
                vistaPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(vistaPrincipal.getText());
                break;
            case "-":
                resultado = valor1 - valor2;
                vistaPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(vistaPrincipal.getText());
                break;
            case "*":
                resultado = valor1 * valor2;
                vistaPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(vistaPrincipal.getText());
                break;
            case "/":
                if(valor2 == 0){
                    vistaPrincipal.setText("Error ");
                    break;
                }else{
                    resultado = valor1 / valor2;
                    vistaPrincipal.setText(resultado + "");
                    valor1 = Double.parseDouble(vistaPrincipal.getText());
                    break;
                }             
        }
        
    }*/
    
    Parseador parseador = new Parseador();
    
    private void resultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosActionPerformed

        String []w = vistaPrincipal.getText().split("=");
     
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
     
        vistaSecundaria.setText(vistaPrincipal.getText());
        vistaPrincipal.setText(resultado);
        cadena = resultado;
        
    }//GEN-LAST:event_resultadosActionPerformed

    private void raizcuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizcuadradaActionPerformed
        
        String []w=vistaPrincipal.getText().split("=");
     
        String aux=parseador.parsear(w[w.length-1]);
        resultado=parseador.evaluar(aux);
        cadena="sqrt(" +cadena+")";
        vistaSecundaria.setText(cadena);

        resultado=Math.sqrt(Float.parseFloat(resultado))+"";
        System.out.println(resultado);
        cadena=resultado;
        vistaPrincipal.setText(cadena); 
        
    }//GEN-LAST:event_raizcuadradaActionPerformed

    private void unoentrexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoentrexActionPerformed
        
        cadena = "1/(" + cadena + ")";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_unoentrexActionPerformed

    private void memoriamenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriamenosActionPerformed
        
        MEMORIA = MEMORIA - Double.parseDouble(vistaPrincipal.getText());
        Memory.setVisible(true);
        
    }//GEN-LAST:event_memoriamenosActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        
        cadena = cadena+"%";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_porcentajeActionPerformed

    private void MasyMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasyMenosActionPerformed
        
       String []w = vistaPrincipal.getText().split("=");
     
       String aux = parseador.parsear(w[w.length-1]);
       resultado = parseador.evaluar(aux);
        
       double nu1 = 0, nu2, nu3;
       nu2 = Double.parseDouble(resultado);
       nu3 = nu1 - nu2;
       cadena = nu3 + "";
       vistaPrincipal.setText(nu3 + " ");
        
    }//GEN-LAST:event_MasyMenosActionPerformed

    private void memoriamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriamasActionPerformed
              
        MEMORIA = MEMORIA + Double.parseDouble(vistaPrincipal.getText());
        Memory.setVisible(true);
        
    }//GEN-LAST:event_memoriamasActionPerformed

    private void parentesis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis1ActionPerformed
        
        cadena = cadena+"(";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_parentesis1ActionPerformed

    private void memoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriasActionPerformed

        String []w = vistaPrincipal.getText().split("=");
     
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        
        MEMORIA = Double.parseDouble(resultado);
        
        vistaPrincipal.setText(MEMORIA + "");
        Memory.setVisible(true);
        cadena = resultado;
        
    }//GEN-LAST:event_memoriasActionPerformed

    private void flechitaXDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechitaXDActionPerformed
        
        String aux = "";
        for(int i = 0 ; i < cadena.length() -1;i++) aux += cadena.charAt(i);
        cadena = aux;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_flechitaXDActionPerformed

    private void memoriacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriacActionPerformed
        
        MEMORIA = 0;
        Memory.setVisible(false);
        
    }//GEN-LAST:event_memoriacActionPerformed

    private void arcotengenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcotengenteActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "atan(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.atan(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_arcotengenteActionPerformed

    private void tangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangenteActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "tan(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.tan(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_tangenteActionPerformed

    private void BorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorradoActionPerformed
        
        resultado = "0";
        cadena = "";
        String aux = "";
        vistaSecundaria.setText(aux);
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_BorradoActionPerformed

    private void memoriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriarActionPerformed
        
        cadena = cadena + MEMORIA;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_memoriarActionPerformed

    private void arcosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcosenoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "asen(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.asin(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_arcosenoActionPerformed

    private void senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "sen(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.sin(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_senoActionPerformed

    private void arcocosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcocosenoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "acos(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.acos(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_arcocosenoActionPerformed

    private void cosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosenoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "cos(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.cos(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_cosenoActionPerformed

    private void raizdealgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizdealgoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
     
        String aux = parseador.parsear("(" + w[w.length-1] + ")^(1/3)");
        resultado = parseador.evaluar(aux); 
        vistaSecundaria.setText("3√" + vistaPrincipal.getText());
        
        vistaPrincipal.setText(resultado);
        cadena = resultado;
        
    }//GEN-LAST:event_raizdealgoActionPerformed

    private void aGradianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aGradianesActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "Grad(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.toDegrees(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_aGradianesActionPerformed

    private void NumeroEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroEulerActionPerformed
        
        cadena = cadena + Math.E+"";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_NumeroEulerActionPerformed

    private void NumeroPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroPiActionPerformed
        
        cadena = cadena + Math.PI+"";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_NumeroPiActionPerformed

    private void xelevadoalcuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xelevadoalcuadradoActionPerformed
        
        cadena = cadena+"^2";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_xelevadoalcuadradoActionPerformed

    private void xelevadoaalgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xelevadoaalgoActionPerformed
        
        cadena = cadena+"^";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_xelevadoaalgoActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "ln(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.log(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_expActionPerformed

    private void aRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRadianesActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "Rad(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.toRadians(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_aRadianesActionPerformed

    private void elevado10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevado10ActionPerformed
       
        String []w = vistaPrincipal.getText().split("=");
     
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux); 
        vistaSecundaria.setText("powten(" + vistaPrincipal.getText() + ")");
        
        valor1 = Double.parseDouble(resultado + "");
        
        vistaPrincipal.setText("" + Math.pow(10, valor1) + "");
        cadena = resultado;
        
    }//GEN-LAST:event_elevado10ActionPerformed

    private void imaginarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imaginarioActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
  
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "(" +cadena+")!";
        vistaSecundaria.setText(cadena);

        float x = Math.abs(Float.parseFloat(resultado));
        for(float j=(x-1);j>0;j--) x=x*j;

        resultado = x+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_imaginarioActionPerformed

    private void logaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logaritmoActionPerformed
        
        String []w = vistaPrincipal.getText().split("=");
        String aux = parseador.parsear(w[w.length-1]);
        resultado = parseador.evaluar(aux);
        cadena = "log(" + cadena + ")";
        vistaSecundaria.setText(cadena);

        resultado = Math.log10(Float.parseFloat(resultado))+"";
        cadena = resultado;
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_logaritmoActionPerformed

    private void xelevadoalcuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xelevadoalcuboActionPerformed
        
        cadena = cadena+"^3";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_xelevadoalcuboActionPerformed

    private void parentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis2ActionPerformed
        
        cadena = cadena+")";
        vistaPrincipal.setText(cadena);
        
    }//GEN-LAST:event_parentesis2ActionPerformed

    private void vistaSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vistaSecundariaActionPerformed

    private void vistaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vistaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrado;
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton MasyMenos;
    private javax.swing.JLabel Memory;
    private javax.swing.JButton Numero0;
    private javax.swing.JButton Numero1;
    private javax.swing.JButton Numero2;
    private javax.swing.JButton Numero3;
    private javax.swing.JButton Numero4;
    private javax.swing.JButton Numero5;
    private javax.swing.JButton Numero6;
    private javax.swing.JButton Numero7;
    private javax.swing.JButton Numero8;
    private javax.swing.JButton Numero9;
    private javax.swing.JButton NumeroEuler;
    private javax.swing.JButton NumeroPi;
    private javax.swing.JButton aGradianes;
    private javax.swing.JButton aRadianes;
    private javax.swing.JButton arcocoseno;
    private javax.swing.JButton arcoseno;
    private javax.swing.JButton arcotengente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coseno;
    private javax.swing.JButton division;
    private javax.swing.JButton elevado10;
    private javax.swing.JButton exp;
    private javax.swing.JButton flechitaXD;
    private javax.swing.JButton imaginario;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logaritmo;
    private javax.swing.JButton memoriac;
    private javax.swing.JButton memoriamas;
    private javax.swing.JButton memoriamenos;
    private javax.swing.JButton memoriar;
    private javax.swing.JButton memorias;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton parentesis1;
    private javax.swing.JButton parentesis2;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton punto;
    private javax.swing.JButton raizcuadrada;
    private javax.swing.JButton raizdealgo;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultados;
    private javax.swing.JButton seno;
    private javax.swing.JButton suma;
    private javax.swing.JButton tangente;
    private javax.swing.JButton unoentrex;
    private javax.swing.JTextField vistaPrincipal;
    private javax.swing.JTextField vistaSecundaria;
    private javax.swing.JButton xelevadoaalgo;
    private javax.swing.JButton xelevadoalcuadrado;
    private javax.swing.JButton xelevadoalcubo;
    // End of variables declaration//GEN-END:variables
}
